# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia', models.IntegerField(default=0)),
                ('periodo', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cientifico', models.CharField(max_length=20)),
                ('nome_popular', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Incide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidencia', models.IntegerField(default=0)),
                ('periodo', models.DurationField()),
                ('doenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Doenca')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apresentacao', models.CharField(max_length=300)),
                ('nome_venda', models.CharField(max_length=20)),
                ('classe_terapeutica', models.CharField(max_length=20)),
                ('principio_ativo', models.CharField(max_length=20)),
                ('laboratorio', models.CharField(max_length=20)),
                ('hospitalar', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Refere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosagem', models.IntegerField(default=0)),
                ('doenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Doenca')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Medicamento')),
            ],
        ),
        migrations.AddField(
            model_name='refere',
            name='sintoma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Sintoma'),
        ),
        migrations.AddField(
            model_name='refere',
            name='termo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Termo'),
        ),
        migrations.AddField(
            model_name='incide',
            name='regiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Regiao'),
        ),
        migrations.AddField(
            model_name='causa',
            name='doenca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Doenca'),
        ),
        migrations.AddField(
            model_name='causa',
            name='sintoma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Sintoma'),
        ),
        migrations.AddField(
            model_name='busca',
            name='regiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Regiao'),
        ),
        migrations.AddField(
            model_name='busca',
            name='termo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Termo'),
        ),
    ]
