# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_auto_20161117_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='registro',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
