# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_auto_20161117_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='laboratorio',
        ),
    ]
