# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_auto_20161124_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='hospitalar',
        ),
    ]
