# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_auto_20161125_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doenca',
            name='nome_cientifico',
        ),
        migrations.AlterField(
            model_name='doenca',
            name='nome_popular',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
