# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_auto_20161125_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busca',
            name='regiao',
        ),
        migrations.RemoveField(
            model_name='busca',
            name='sintoma',
        ),
        migrations.AddField(
            model_name='previsao',
            name='regiao',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estoque.Regiao'),
        ),
        migrations.AlterField(
            model_name='previsao',
            name='resultado',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='previsao',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Busca',
        ),
    ]
