# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_previsao_sintoma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relaciona',
            name='previsao',
        ),
        migrations.RemoveField(
            model_name='relaciona',
            name='sintoma',
        ),
        migrations.DeleteModel(
            name='Relaciona',
        ),
    ]
