from pyt import trends
import csv

trend = trends()

terms = [
    "Cansaco",
"Dor atras dos olhos",
"Dor de cabeca",
"Dor nas articulacoes",
"Dor muscular",
"Dor nos ossos",
"Febre",
"Manchas vermelhas pelo corpo",
"Moleza",
"Nausea",
"Perda de paladar e apetite",
"Tontura",
"Vomito",
"Aumento do tamanho do baco",
"Aumento do tamanho do figado",
"Diarreia",
"Dor de cabeca",
"Dor no corpo",
"Fadiga",
"Febre",
"Irritacao sobre a pele",
"Mal estar",
"Nausea",
"Surgimento de nodulos",
"Vomito",
"Calafrios",
"Diarreia",
"Dor abdominal",
"Dor muscular",
"Febre",
"sangue nas fezes",
"Tosse",
"Aumento do tamanho do baco",
"Arritmia",
"Dor de cabeca",
"falta de apetite",
"Febre",
"machas rosadas no tronco",
"Mal estar",
"tosse",
"Dor abdominal",
"Dor de cabeca",
"Dor lombar",
"Febre",
"Hemorragias",
"Hipotensao",
"Nausea",
"Rubor facial",
"Arritmia",
"Vomito",
"Aparecimento de feridas na pele",
"crescimento progressivo das feridas",
"anemia",
"Aumento do tamanho do baco",
"Aumento do tamanho do figado",
"falta de apetite",
"Febre",
"indisposicao",
"Palidez",
"perda de peso",
"Diarreia",
"Dor de cabeca",
"dor no corpo",
"Febre",
"Hemorragias",
"Ictericia",
"insuficiencia hepatica",
"insuficiencia renal",
"insuficiencia respiratoria",
"tosse",
"Vomito",
"Aumento do tamanho do baco",
"Calafrios",
"convulsoes",
"desorientacao",
"Dor de cabeca",
"Dor muscular",
"Febre",
"Arritmia",
"Vomito",
"confusao mental",
"convulsoes",
"Dificuldade de concentracao",
"Dor de cabeca",
"falta de apetite",
"Febre",
"Fotossensibilidade",
"Nausea",
"Pescoco rigido",
"sonolencia",
"vomito",
"Espasmos musculares",
"Febre",
"Hipertensao",
"rigidez no maxilar",
"Rigidez nos musculos de pescoco e nuca",
"Rigidez nos musculos do abdomen",
"Sudorese",
"Arritmia"
]

print(trend.get_trends_safe(terms))
