# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doenca',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='id',
        ),
        migrations.RemoveField(
            model_name='regiao',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sintoma',
            name='id',
        ),
        migrations.RemoveField(
            model_name='termo',
            name='id',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='registro',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='nome_cientifico',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='regiao',
            name='nome',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sintoma',
            name='nome',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='termo',
            name='nome',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
