# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20161109_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='registro',
            field=models.IntegerField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
