# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_auto_20161125_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incide',
            name='doenca',
        ),
        migrations.RemoveField(
            model_name='incide',
            name='regiao',
        ),
        migrations.DeleteModel(
            name='Incide',
        ),
    ]
